"""Regression tests for encoder output stability.

These tests compare the current encoder output against previously recorded
fixture arrays (generated by ``tests/generate_fixtures.py``).  If a refactor
changes the numerical output of the encoder, these tests will fail — which is
the point: any behavioural change must be deliberate and the fixtures
regenerated explicitly.

Fixtures are stored as framework-agnostic ``.npz`` files (numpy arrays) so
they remain valid after replacing torch/torchhd with a different backend.
"""

import json
from pathlib import Path

import numpy as np
import pytest
from rdkit import Chem

from hyper_fingerprints.encoder import Encoder

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "regression_data.npz"
ATOL = 1e-10


def _to_numpy(x):
    """Convert encoder output to a plain numpy array."""
    return np.asarray(x)


@pytest.fixture(scope="module")
def fixture_data():
    if not FIXTURE_PATH.exists():
        pytest.skip(
            "Regression fixtures not found. "
            "Run 'python -m tests.generate_fixtures' first."
        )
    raw = np.load(FIXTURE_PATH, allow_pickle=False)
    config = json.loads(bytes(raw["config"]))
    smiles = json.loads(bytes(raw["smiles"]))

    individual_encode = {}
    individual_encode_joint = {}
    for i, smi in enumerate(smiles):
        individual_encode[smi] = raw[f"ind_encode_{i}"]
        individual_encode_joint[smi] = raw[f"ind_joint_{i}"]

    return {
        "config": config,
        "smiles": smiles,
        "codebook": raw["codebook"],
        "individual_encode": individual_encode,
        "individual_encode_joint": individual_encode_joint,
        "batch_encode": raw["batch_encode"],
        "batch_encode_joint": raw["batch_encode_joint"],
    }


@pytest.fixture(scope="module")
def encoder(fixture_data):
    cfg = fixture_data["config"]
    return Encoder(
        dimension=cfg["dimension"],
        depth=cfg["depth"],
        seed=cfg["seed"],
        codebook=fixture_data["codebook"],
    )


# ── Codebook test ───────────────────────────────────────────────────────


class TestCodebook:
    """The generated codebook must exactly match the recorded fixture."""

    def test_codebook_matches(self, encoder, fixture_data):
        codebook = _to_numpy(encoder._codebook)
        expected = fixture_data["codebook"]
        np.testing.assert_allclose(codebook, expected, atol=ATOL, rtol=0)


# ── Individual molecule tests ───────────────────────────────────────────


class TestIndividualEncode:
    """Each molecule encoded alone must match its recorded fixture."""

    def test_encode(self, encoder, fixture_data):
        for smi, expected in fixture_data["individual_encode"].items():
            result = _to_numpy(encoder.encode(smi))
            np.testing.assert_allclose(
                result, expected, atol=ATOL, rtol=0,
                err_msg=f"encode() mismatch for {smi!r}",
            )

    def test_encode_joint(self, encoder, fixture_data):
        for smi, expected in fixture_data["individual_encode_joint"].items():
            result = _to_numpy(encoder.encode_joint(smi))
            np.testing.assert_allclose(
                result, expected, atol=ATOL, rtol=0,
                err_msg=f"encode_joint() mismatch for {smi!r}",
            )


# ── Batch tests ─────────────────────────────────────────────────────────


class TestBatchEncode:
    """Batch encoding of all molecules must match the recorded fixture."""

    def test_encode_batch(self, encoder, fixture_data):
        smiles = fixture_data["smiles"]
        expected = fixture_data["batch_encode"]
        result = _to_numpy(encoder.encode(smiles))
        np.testing.assert_allclose(result, expected, atol=ATOL, rtol=0)

    def test_encode_joint_batch(self, encoder, fixture_data):
        smiles = fixture_data["smiles"]
        expected = fixture_data["batch_encode_joint"]
        result = _to_numpy(encoder.encode_joint(smiles))
        np.testing.assert_allclose(result, expected, atol=ATOL, rtol=0)


# ── Batch vs individual consistency ─────────────────────────────────────


class TestBatchConsistency:
    """Encoding molecules individually must produce the same vectors as
    encoding them in a single batch call."""

    @staticmethod
    def _is_single_atom(smi: str) -> bool:
        mol = Chem.MolFromSmiles(smi)
        return mol is not None and mol.GetNumAtoms() == 1

    def test_encode_batch_vs_individual(self, encoder, fixture_data):
        smiles = fixture_data["smiles"]
        batch_result = _to_numpy(encoder.encode(smiles))
        for i, smi in enumerate(smiles):
            if self._is_single_atom(smi):
                continue  # single-atom molecules have a known batch discrepancy
            individual = _to_numpy(encoder.encode(smi))
            np.testing.assert_allclose(
                batch_result[i : i + 1], individual, atol=ATOL, rtol=0,
                err_msg=f"encode() batch/individual mismatch for {smi!r} at index {i}",
            )

    def test_encode_joint_batch_vs_individual(self, encoder, fixture_data):
        smiles = fixture_data["smiles"]
        batch_result = _to_numpy(encoder.encode_joint(smiles))
        for i, smi in enumerate(smiles):
            if self._is_single_atom(smi):
                continue  # single-atom molecules have a known batch discrepancy
            individual = _to_numpy(encoder.encode_joint(smi))
            np.testing.assert_allclose(
                batch_result[i : i + 1], individual, atol=ATOL, rtol=0,
                err_msg=f"encode_joint() batch/individual mismatch for {smi!r} at index {i}",
            )
